version: 0.0
os: linux
files:
  - source: lambda_function.zip
    destination: /var/www/html/lambda
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_application.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_application.sh
      timeout: 300
      runas: ec2-user
