version: 0.0
Resources:
  - Name: MyTodoLambda
    Type: AWS::Lambda::Function
    Source:
      Locations:
        - Location: build/lambda_function.zip
Hooks:
  AfterInstall:
    - Location: scripts/after_install.sh
      Timeout: 300
