version: 0.0
Resources:
  - MyTodoLambda:
      Type: AWS::Lambda::Function
      Properties:
        Name: MyTodoLambda
        Alias: live
        CurrentVersion: auto
        TargetVersion: auto
Hooks:
  AfterAllowTestTraffic:
    - Location: scripts/after_install.sh
      Timeout: 300
