version: 0.0

Resources:
  - MyTodoLambda:
      Type: AWS::Lambda::Function
      Properties:
        Name: MyTodoLambda          # Your Lambda function name here
        Alias: live                 # Optional: your Lambda alias name
        CurrentVersion: true

Hooks:
  AfterAllowTestTraffic:
    - location: scripts/after_install.sh
      timeout: 300

