version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t backend/
      - aws configure set region us-east-1 # Replace with your region
  build:
    commands:
      - echo "Packaging Lambda function"
      - mkdir -p build
      - cd backend
      - zip -r ../build/lambda_function.zip .
      - cd ..
      - ls -la build/
  post_build:
    commands:
      - echo "Uploading artifact to S3 bucket mytodo-artifacts"
      - aws s3 cp build/lambda_function.zip s3://mytodo-artifacts/lambda_function.zip
      - echo "Copying appspec.yml to build directory"
      - cp appspec.yml build/appspec.yml
      - echo "Build and upload complete"

artifacts:
  files:
    - build/lambda_function.zip
    - build/appspec.yml
  discard-paths: yes
