version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Match your Lambda runtime
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t backend/ # Install dependencies to backend/
  build:
    commands:
      - echo "Creating build directory and lambda_function.zip"
      - mkdir -p build
      - cd backend
      - zip -r ../build/lambda_function.zip . # Package all files in backend/
      - cd ..
      - ls -la build/ # Debug: verify ZIP file exists
      - unzip -l build/lambda_function.zip # Debug: check ZIP contents
      - aws lambda update-function-code --function-name MyTodoLambda --zip-file fileb://build/lambda_function.zip
  post_build:
    commands:
      - echo "Deployment complete"

artifacts:
  files:
    - build/lambda_function.zip
  discard-paths: yes
